version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo Finished installing
      - npm test

  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Testing